name: portfolio
description: "Daniel Sioson is an experienced mobile and web developer specializing in Android (Java/Kotlin), Flutter, and web technologies."
publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  dart_casing: ^3.0.1
  dio: ^5.11.0
  easy_localization: ^3.0.8
  flutter_svg: ^2.3.0
  path: ^1.9.1
  responsive_builder: ^0.7.1
  timelines_plus: ^2.0.1
  url_launcher: ^6.3.2
  web_smooth_scroll: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/downloads/
    - assets/logos/
    - assets/projects/
    - assets/translations/
